import { Question, Topic } from "@/types/quiz";

const verified = {
  status: "verified" as const,
  quranReferenceChecked: true,
  arabicChecked: true,
  translationChecked: true,
  hadithReferenceChecked: true,
  hadithGradeChecked: true,
};

const draft = {
  status: "needs-verification" as const,
  quranReferenceChecked: false,
  arabicChecked: false,
  translationChecked: false,
  hadithReferenceChecked: false,
  hadithGradeChecked: false,
};

function makeLessons(topicId: string, entries: string[]): Topic["lessons"] {
  return entries.map((title, index) => ({
    id: `${topicId}-${index + 1}`,
    topicId,
    title,
    description: index === 0 ? "Build a clear foundation from the evidence." : "Learn, practice, and revisit the key evidence.",
    questionIds: [],
    order: index + 1,
  }));
}

export const topics: Topic[] = [
  {
    id: "following-the-prophet",
    title: "Following the Prophet ﷺ",
    shortTitle: "Sunnah",
    description: "Learn the Qur'anic and Prophetic evidence for following Muhammad ﷺ.",
    icon: "sunna",
    accent: "emerald",
    lessons: makeLessons("following-the-prophet", ["Who is the Messenger?", "Obeying the Messenger", "Holding to the Sunnah", "Love of Allah", "What he commands", "What he prohibits", "The Companions", "Sunnah in worship", "Sunnah in character", "Final challenge"]),
  },
  {
    id: "tawhid",
    title: "Tawḥīd",
    shortTitle: "Tawhid",
    description: "Explore worshipping Allah alone, du'a, reliance, and His rights.",
    icon: "compass",
    accent: "gold",
    lessons: makeLessons("tawhid", ["What is Tawḥīd?", "Worship Allah alone", "Du'a and reliance"]),
  },
  {
    id: "salah",
    title: "Ṣalāh",
    shortTitle: "Salah",
    description: "Strengthen your understanding of prayer and following its Prophetic example.",
    icon: "mosque",
    accent: "blue",
    lessons: makeLessons("salah", ["Why we pray", "Establishing prayer", "Pray as he prayed"]),
  },
  {
    id: "quran",
    title: "Qur'an",
    shortTitle: "Qur'an",
    description: "Reflect on the Book as guidance, mercy, and a source of light.",
    icon: "book",
    accent: "violet",
    lessons: makeLessons("quran", ["A book of guidance", "Recite and reflect", "Carry the message"]),
  },
  {
    id: "parents",
    title: "Parents",
    shortTitle: "Parents",
    description: "Study the command to show ihsan, gratitude, and gentle speech.",
    icon: "heart",
    accent: "rose",
    lessons: makeLessons("parents", ["The command to be good", "A mother's right", "Gentle speech"]),
  },
  {
    id: "good-character",
    title: "Good Character",
    shortTitle: "Character",
    description: "Practice truthfulness, patience, humility, and forgiveness.",
    icon: "sparkle",
    accent: "amber",
    lessons: makeLessons("good-character", ["Truthfulness", "Patience", "The best character"]),
  },
  {
    id: "brotherhood",
    title: "Muslim Brotherhood",
    shortTitle: "Brotherhood",
    description: "Learn how faith shapes the way we treat and care for one another.",
    icon: "users",
    accent: "teal",
    lessons: makeLessons("brotherhood", ["Love what is good", "Make peace", "Guard the tongue"]),
  },
  {
    id: "knowledge",
    title: "Seeking Knowledge",
    shortTitle: "Knowledge",
    description: "Discover the virtue of knowledge and asking with humility.",
    icon: "graduation",
    accent: "indigo",
    lessons: makeLessons("knowledge", ["Those who know", "Ask and learn", "Knowledge in action"]),
  },
  {
    id: "dhikr-dua",
    title: "Dhikr & Du'a",
    shortTitle: "Dhikr",
    description: "Keep the heart present through remembrance, gratitude, and supplication.",
    icon: "moon",
    accent: "cyan",
    lessons: makeLessons("dhikr-dua", ["Hearts find rest", "Remember often", "Ask Allah"]),
  },
  {
    id: "fasting",
    title: "Fasting",
    shortTitle: "Fasting",
    description: "Learn the purpose and promise of fasting in Ramaḍān.",
    icon: "crescent",
    accent: "orange",
    lessons: makeLessons("fasting", ["Why we fast", "Ramaḍān", "The reward of taqwa"]),
  },
  {
    id: "charity",
    title: "Charity",
    shortTitle: "Charity",
    description: "Grow in generosity through zakāh, ṣadaqah, and caring for others.",
    icon: "hand-heart",
    accent: "green",
    lessons: makeLessons("charity", ["The seed of charity", "Give sincerely", "Care for the poor"]),
  },
  {
    id: "avoiding-sins",
    title: "Avoiding Sins",
    shortTitle: "Avoid sins",
    description: "Recognize the habits that harm the heart and the bonds between people.",
    icon: "shield",
    accent: "slate",
    lessons: makeLessons("avoiding-sins", ["Guard the tongue", "Humility", "Repentance"]),
  },
];

export const questions: Question[] = [
  {
    id: "sunnah-001",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-2",
    difficulty: "easy",
    type: "multiple-choice",
    question: "What does this āyah teach?",
    evidence: { type: "quran", arabic: "مَّن يُطِعِ ٱلرَّسُولَ فَقَدْ أَطَاعَ ٱللَّهَ", translation: "Whoever obeys the Messenger has obeyed Allah.", reference: "An-Nisa 4:80" },
    answers: [
      { id: "a", text: "Obeying the Messenger ﷺ is obedience to Allah" },
      { id: "b", text: "Following the Messenger ﷺ is optional" },
      { id: "c", text: "Only scholars must follow him ﷺ" },
      { id: "d", text: "The Sunnah is separate from faith" },
    ],
    correctAnswer: "a",
    explanation: "Allah connects obedience to His Messenger ﷺ with obedience to Himself.",
    xp: 100,
    verification: verified,
  },
  {
    id: "sunnah-002",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-4",
    difficulty: "medium",
    type: "multiple-choice",
    question: "According to this āyah, what is a sign of truly loving Allah?",
    evidence: { type: "quran", arabic: "قُلْ إِن كُنتُمْ تُحِبُّونَ ٱللَّهَ فَٱتَّبِعُونِي يُحْبِبْكُمُ ٱللَّهُ", translation: "Say, [O Muhammad], 'If you should love Allah, then follow me, [so] Allah will love you.'", reference: "Ali 'Imran 3:31" },
    answers: [
      { id: "a", text: "Following the Messenger ﷺ" },
      { id: "b", text: "Keeping love only in the heart" },
      { id: "c", text: "Seeking praise from people" },
      { id: "d", text: "Avoiding all action" },
    ],
    correctAnswer: "a",
    explanation: "The āyah gives following the Messenger ﷺ as the practical sign of love of Allah.",
    xp: 100,
    verification: verified,
  },
  {
    id: "sunnah-003",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-3",
    difficulty: "scholar",
    type: "finish-ayah",
    question: "Complete the āyah: وَمَا آتَاكُمُ الرَّسُولُ _______",
    evidence: { type: "quran", arabic: "وَمَا آتَاكُمُ ٱلرَّسُولُ فَخُذُوهُ وَمَا نَهَاكُمْ عَنْهُ فَٱنتَهُوا۟", translation: "And whatever the Messenger has given you - take; and what he has forbidden you - refrain from.", reference: "Al-Hashr 59:7" },
    answers: [
      { id: "a", text: "فَخُذُوهُ" },
      { id: "b", text: "فَاتْرُكُوهُ" },
      { id: "c", text: "فَاسْأَلُوهُ" },
      { id: "d", text: "فَاكْتُبُوهُ" },
    ],
    correctAnswer: "a",
    explanation: "Believers are instructed to take what the Messenger ﷺ gives and refrain from what he forbids.",
    xp: 150,
    verification: verified,
  },
  {
    id: "sunnah-004",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-4",
    difficulty: "easy",
    type: "true-false",
    question: "True or false: The Qur'an presents following the Messenger ﷺ as a path to Allah's love.",
    evidence: { type: "quran", arabic: "قُلْ إِن كُنتُمْ تُحِبُّونَ ٱللَّهَ فَٱتَّبِعُونِي يُحْبِبْكُمُ ٱللَّهُ", translation: "Say, [O Muhammad], 'If you should love Allah, then follow me, [so] Allah will love you.'", reference: "Ali 'Imran 3:31" },
    answers: [{ id: "a", text: "True" }, { id: "b", text: "False" }],
    correctAnswer: "a",
    explanation: "This āyah directly ties following the Messenger ﷺ to Allah loving the believer.",
    xp: 100,
    verification: verified,
  },
  {
    id: "sunnah-005",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-2",
    difficulty: "medium",
    type: "multiple-choice",
    question: "What does the following ḥadīth teach?",
    evidence: { type: "hadith", arabic: "مَنْ أَطَاعَنِي فَقَدْ أَطَاعَ اللَّهَ، وَمَنْ عَصَانِي فَقَدْ عَصَى اللَّهَ", translation: "Whoever obeys me has obeyed Allah, and whoever disobeys me has disobeyed Allah.", reference: "Sahih al-Bukhari 7137", collection: "Sahih al-Bukhari", hadithNumber: "7137", grade: "Sahih" },
    answers: [
      { id: "a", text: "Obedience to the Messenger ﷺ matters" },
      { id: "b", text: "The Messenger ﷺ spoke only about history" },
      { id: "c", text: "Obedience is not connected to worship" },
      { id: "d", text: "There is no difference between truth and falsehood" },
    ],
    correctAnswer: "a",
    explanation: "The Prophet ﷺ describes obedience to him as obedience to Allah, showing the authority of the Sunnah.",
    xp: 125,
    verification: verified,
  },
  {
    id: "sunnah-006",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-3",
    difficulty: "scholar",
    type: "true-false",
    question: "True or false: A religious practice introduced after the Prophet's ﷺ guidance is accepted simply because people are used to it.",
    evidence: { type: "hadith", arabic: "مَنْ أَحْدَثَ فِي أَمْرِنَا هَذَا مَا لَيْسَ فِيهِ فَهُوَ رَدٌّ", translation: "Whoever introduces into this matter of ours that which is not from it, it is rejected.", reference: "Sahih al-Bukhari 2697", collection: "Sahih al-Bukhari", hadithNumber: "2697", grade: "Sahih" },
    answers: [{ id: "a", text: "True" }, { id: "b", text: "False" }],
    correctAnswer: "b",
    explanation: "The ḥadīth teaches that a religious matter without Prophetic guidance is rejected.",
    xp: 150,
    verification: verified,
  },
  {
    id: "sunnah-007",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-5",
    difficulty: "medium",
    type: "multiple-choice",
    question: "When believers differ, what does this āyah direct them to do?",
    evidence: { type: "quran", arabic: "فَإِن تَنَازَعْتُمْ فِي شَيْءٍ فَرُدُّوهُ إِلَى ٱللَّهِ وَٱلرَّسُولِ", translation: "If you disagree over anything, refer it to Allah and the Messenger.", reference: "An-Nisa 4:59" },
    answers: [
      { id: "a", text: "Return the matter to Allah and the Messenger ﷺ" },
      { id: "b", text: "Choose whichever view is most popular" },
      { id: "c", text: "Avoid learning the evidence" },
      { id: "d", text: "Let anger decide" },
    ],
    correctAnswer: "a",
    explanation: "Revelation is the reference point when believers disagree, not popularity or personal preference.",
    xp: 125,
    verification: verified,
  },
  {
    id: "sunnah-008",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-1",
    difficulty: "easy",
    type: "multiple-choice",
    question: "Why is the Messenger ﷺ an example for believers?",
    evidence: { type: "quran", arabic: "لَّقَدْ كَانَ لَكُمْ فِي رَسُولِ ٱللَّهِ أُسْوَةٌ حَسَنَةٌ", translation: "There has certainly been for you in the Messenger of Allah an excellent pattern.", reference: "Al-Ahzab 33:21" },
    answers: [
      { id: "a", text: "He is an excellent pattern to follow" },
      { id: "b", text: "He was only an example for his companions" },
      { id: "c", text: "His example applies only to history" },
      { id: "d", text: "The āyah gives no guidance" },
    ],
    correctAnswer: "a",
    explanation: "Allah identifies the Messenger ﷺ as an excellent pattern for those who hope in Allah and the Last Day.",
    xp: 100,
    verification: verified,
  },
  {
    id: "sunnah-009",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-6",
    difficulty: "medium",
    type: "true-false",
    question: "True or false: What the Messenger ﷺ forbids is something a believer should refrain from.",
    evidence: { type: "quran", arabic: "وَمَا نَهَاكُمْ عَنْهُ فَٱنتَهُوا۟", translation: "And what he has forbidden you - refrain from.", reference: "Al-Hashr 59:7" },
    answers: [{ id: "a", text: "True" }, { id: "b", text: "False" }],
    correctAnswer: "a",
    explanation: "The command in Al-Hashr 59:7 is clear: refrain from what the Messenger ﷺ forbids.",
    xp: 100,
    verification: verified,
  },
  {
    id: "sunnah-010",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-8",
    difficulty: "easy",
    type: "multiple-choice",
    question: "What should a believer do when the Messenger ﷺ calls them to a matter that gives them life?",
    evidence: { type: "quran", arabic: "ٱسْتَجِيبُوا۟ لِلَّهِ وَلِلرَّسُولِ إِذَا دَعَاكُمْ لِمَا يُحْيِيكُمْ", translation: "Respond to Allah and to the Messenger when he calls you to that which gives you life.", reference: "Al-Anfal 8:24" },
    answers: [
      { id: "a", text: "Respond" },
      { id: "b", text: "Wait for people to approve" },
      { id: "c", text: "Ignore the call" },
      { id: "d", text: "Replace it with personal opinion" },
    ],
    correctAnswer: "a",
    explanation: "Guidance is life for the heart, so the āyah calls believers to respond to Allah and His Messenger ﷺ.",
    xp: 100,
    verification: verified,
  },
  {
    id: "tawhid-001",
    topicId: "tawhid",
    lessonId: "tawhid-1",
    difficulty: "easy",
    type: "multiple-choice",
    question: "According to this āyah, what is the purpose for which jinn and mankind were created?",
    evidence: { type: "quran", arabic: "وَمَا خَلَقْتُ ٱلْجِنَّ وَٱلْإِنسَ إِلَّا لِيَعْبُدُونِ", translation: "I did not create jinn and mankind except to worship Me.", reference: "Adh-Dhariyat 51:56" },
    answers: [{ id: "a", text: "To worship Allah" }, { id: "b", text: "To seek fame" }, { id: "c", text: "To avoid responsibility" }, { id: "d", text: "To compete for wealth" }],
    correctAnswer: "a",
    explanation: "Worshipping Allah alone is the purpose named in this āyah.",
    xp: 100,
    verification: verified,
  },
  {
    id: "tawhid-002",
    topicId: "tawhid",
    lessonId: "tawhid-2",
    difficulty: "easy",
    type: "finish-ayah",
    question: "Complete the opening of Al-Fatihah: إِيَّاكَ نَعْبُدُ وَإِيَّاكَ _______",
    evidence: { type: "quran", arabic: "إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ", translation: "It is You we worship and You we ask for help.", reference: "Al-Fatihah 1:5" },
    answers: [{ id: "a", text: "نَسْتَعِينُ" }, { id: "b", text: "نَسْتَغْفِرُ" }, { id: "c", text: "نَشْكُرُ" }, { id: "d", text: "نَسْأَلُ" }],
    correctAnswer: "a",
    explanation: "The believer directs worship and seeking help to Allah alone.",
    xp: 150,
    verification: verified,
  },
  {
    id: "salah-001",
    topicId: "salah",
    lessonId: "salah-2",
    difficulty: "easy",
    type: "multiple-choice",
    question: "What command is given in this āyah?",
    evidence: { type: "quran", arabic: "وَأَقِمِ ٱلصَّلَاةَ لِذِكْرِي", translation: "And establish prayer for My remembrance.", reference: "Taha 20:14" },
    answers: [{ id: "a", text: "Establish prayer" }, { id: "b", text: "Give up remembrance" }, { id: "c", text: "Delay every prayer" }, { id: "d", text: "Pray for people to see" }],
    correctAnswer: "a",
    explanation: "Prayer is established for the remembrance of Allah.",
    xp: 100,
    verification: verified,
  },
  {
    id: "salah-002",
    topicId: "salah",
    lessonId: "salah-3",
    difficulty: "medium",
    type: "multiple-choice",
    question: "What principle does the Prophet ﷺ teach about how to pray?",
    evidence: { type: "hadith", arabic: "صَلُّوا كَمَا رَأَيْتُمُونِي أُصَلِّي", translation: "Pray as you have seen me praying.", reference: "Sahih al-Bukhari 631", collection: "Sahih al-Bukhari", hadithNumber: "631", grade: "Sahih" },
    answers: [{ id: "a", text: "Follow the Prophetic example" }, { id: "b", text: "Invent a different prayer" }, { id: "c", text: "Prayer has no form" }, { id: "d", text: "Only pray in public" }],
    correctAnswer: "a",
    explanation: "The ḥadīth makes the Prophet's ﷺ prayer the model for believers.",
    xp: 125,
    verification: verified,
  },
  {
    id: "quran-001",
    topicId: "quran",
    lessonId: "quran-1",
    difficulty: "easy",
    type: "multiple-choice",
    question: "How does this āyah describe the Qur'an?",
    evidence: { type: "quran", arabic: "ذَٰلِكَ ٱلْكِتَابُ لَا رَيْبَ فِيهِ هُدًى لِّلْمُتَّقِينَ", translation: "This is the Book about which there is no doubt, a guidance for those conscious of Allah.", reference: "Al-Baqarah 2:2" },
    answers: [{ id: "a", text: "Guidance for those conscious of Allah" }, { id: "b", text: "A book without purpose" }, { id: "c", text: "Only a historical record" }, { id: "d", text: "A text for one nation only" }],
    correctAnswer: "a",
    explanation: "The Qur'an is described as guidance for the people of taqwa.",
    xp: 100,
    verification: verified,
  },
  {
    id: "parents-001",
    topicId: "parents",
    lessonId: "parents-1",
    difficulty: "easy",
    type: "multiple-choice",
    question: "What does Allah command immediately after worshipping Him alone in this āyah?",
    evidence: { type: "quran", arabic: "وَبِٱلْوَالِدَيْنِ إِحْسَانًا", translation: "And to parents, good treatment.", reference: "Al-Isra 17:23" },
    answers: [{ id: "a", text: "Good treatment of parents" }, { id: "b", text: "Avoiding parents" }, { id: "c", text: "Only giving gifts" }, { id: "d", text: "Speaking harshly" }],
    correctAnswer: "a",
    explanation: "The āyah places ihsan to parents alongside the command to worship Allah alone.",
    xp: 100,
    verification: verified,
  },
  {
    id: "character-001",
    topicId: "good-character",
    lessonId: "good-character-1",
    difficulty: "easy",
    type: "true-false",
    question: "True or false: Believers are commanded to be with the truthful.",
    evidence: { type: "quran", arabic: "يَا أَيُّهَا ٱلَّذِينَ آمَنُوا۟ ٱتَّقُوا۟ ٱللَّهَ وَكُونُوا۟ مَعَ ٱلصَّادِقِينَ", translation: "O you who have believed, fear Allah and be with those who are true.", reference: "At-Tawbah 9:119" },
    answers: [{ id: "a", text: "True" }, { id: "b", text: "False" }],
    correctAnswer: "a",
    explanation: "Truthfulness is a quality Allah explicitly commands believers to keep close to.",
    xp: 100,
    verification: verified,
  },
  {
    id: "brotherhood-001",
    topicId: "brotherhood",
    lessonId: "brotherhood-1",
    difficulty: "medium",
    type: "multiple-choice",
    question: "What does complete faith include according to this ḥadīth?",
    evidence: { type: "hadith", arabic: "لَا يُؤْمِنُ أَحَدُكُمْ حَتَّى يُحِبَّ لِأَخِيهِ مَا يُحِبُّ لِنَفْسِهِ", translation: "None of you truly believes until he loves for his brother what he loves for himself.", reference: "Sahih al-Bukhari 13", collection: "Sahih al-Bukhari", hadithNumber: "13", grade: "Sahih" },
    answers: [{ id: "a", text: "Wanting good for your brother" }, { id: "b", text: "Competing in every matter" }, { id: "c", text: "Keeping good only for yourself" }, { id: "d", text: "Avoiding all community" }],
    correctAnswer: "a",
    explanation: "The ḥadīth connects complete faith with sincere care for another believer.",
    xp: 125,
    verification: verified,
  },
  {
    id: "knowledge-001",
    topicId: "knowledge",
    lessonId: "knowledge-1",
    difficulty: "easy",
    type: "multiple-choice",
    question: "Who does this āyah say are not equal?",
    evidence: { type: "quran", arabic: "قُلْ هَلْ يَسْتَوِي ٱلَّذِينَ يَعْلَمُونَ وَٱلَّذِينَ لَا يَعْلَمُونَ", translation: "Say, 'Are those who know equal to those who do not know?'", reference: "Az-Zumar 39:9" },
    answers: [{ id: "a", text: "Those who know and those who do not know" }, { id: "b", text: "The rich and poor only" }, { id: "c", text: "Travelers and residents" }, { id: "d", text: "Young and old" }],
    correctAnswer: "a",
    explanation: "The āyah highlights the distinction and virtue of beneficial knowledge.",
    xp: 100,
    verification: verified,
  },
  {
    id: "dhikr-001",
    topicId: "dhikr-dua",
    lessonId: "dhikr-dua-1",
    difficulty: "easy",
    type: "multiple-choice",
    question: "What brings hearts reassurance according to this āyah?",
    evidence: { type: "quran", arabic: "أَلَا بِذِكْرِ ٱللَّهِ تَطْمَئِنُّ ٱلْقُلُوبُ", translation: "Unquestionably, in the remembrance of Allah do hearts find rest.", reference: "Ar-Ra'd 13:28" },
    answers: [{ id: "a", text: "The remembrance of Allah" }, { id: "b", text: "Collecting possessions" }, { id: "c", text: "Being praised" }, { id: "d", text: "Avoiding reflection" }],
    correctAnswer: "a",
    explanation: "Dhikr is not just repetition; it is a source of calm and presence for the heart.",
    xp: 100,
    verification: verified,
  },
  {
    id: "fasting-001",
    topicId: "fasting",
    lessonId: "fasting-1",
    difficulty: "easy",
    type: "multiple-choice",
    question: "What is the stated aim of fasting in this āyah?",
    evidence: { type: "quran", arabic: "كُتِبَ عَلَيْكُمُ ٱلصِّيَامُ ... لَعَلَّكُمْ تَتَّقُونَ", translation: "Fasting has been prescribed for you ... that you may become righteous.", reference: "Al-Baqarah 2:183" },
    answers: [{ id: "a", text: "That you may gain taqwa" }, { id: "b", text: "To become known" }, { id: "c", text: "To avoid all food forever" }, { id: "d", text: "To compete with others" }],
    correctAnswer: "a",
    explanation: "Fasting is an act of worship intended to cultivate taqwa, not merely hunger.",
    xp: 100,
    verification: verified,
  },
  {
    id: "charity-001",
    topicId: "charity",
    lessonId: "charity-1",
    difficulty: "medium",
    type: "multiple-choice",
    question: "How does Allah illustrate the reward of spending in His way?",
    evidence: { type: "quran", arabic: "مَّثَلُ ٱلَّذِينَ يُنفِقُونَ أَمْوَالَهُمْ فِي سَبِيلِ ٱللَّهِ كَمَثَلِ حَبَّةٍ أَنبَتَتْ سَبْعَ سَنَابِلَ", translation: "The example of those who spend their wealth in the way of Allah is like a seed that grows seven ears.", reference: "Al-Baqarah 2:261" },
    answers: [{ id: "a", text: "Like a seed that multiplies its harvest" }, { id: "b", text: "Like wealth that disappears without reward" }, { id: "c", text: "Like a debt to people" }, { id: "d", text: "Like a private achievement" }],
    correctAnswer: "a",
    explanation: "The parable shows how Allah multiplies the reward of sincere spending.",
    xp: 125,
    verification: verified,
  },
  {
    id: "sins-001",
    topicId: "avoiding-sins",
    lessonId: "avoiding-sins-1",
    difficulty: "easy",
    type: "true-false",
    question: "True or false: The Qur'an compares backbiting to eating the flesh of one's dead brother.",
    evidence: { type: "quran", arabic: "أَيُحِبُّ أَحَدُكُمْ أَن يَأْكُلَ لَحْمَ أَخِيهِ مَيْتًا فَكَرِهْتُمُوهُ", translation: "Would one of you like to eat the flesh of his brother when dead? You would detest it.", reference: "Al-Hujurat 49:12" },
    answers: [{ id: "a", text: "True" }, { id: "b", text: "False" }],
    correctAnswer: "a",
    explanation: "This powerful comparison shows the ugliness of backbiting and calls believers to guard one another's honor.",
    xp: 100,
    verification: verified,
  },
  {
    id: "review-draft-001",
    topicId: "following-the-prophet",
    lessonId: "following-the-prophet-10",
    difficulty: "scholar",
    type: "multiple-choice",
    question: "Which source should be checked before publishing an Islamic quiz item?",
    evidence: { type: "quran", arabic: "فَاسْأَلُوا أَهْلَ ٱلذِّكْرِ إِن كُنتُمْ لَا تَعْلَمُونَ", translation: "So ask the people of knowledge if you do not know.", reference: "An-Nahl 16:43" },
    answers: [{ id: "a", text: "Qualified people of knowledge" }, { id: "b", text: "An unverified generated answer" }, { id: "c", text: "A random social post" }, { id: "d", text: "A guess" }],
    correctAnswer: "a",
    explanation: "Content about revelation should be checked with reliable scholarship before it is published.",
    xp: 150,
    verification: draft,
  },
];

for (const topic of topics) {
  for (const lesson of topic.lessons) {
    lesson.questionIds = questions.filter((question) => question.lessonId === lesson.id).map((question) => question.id);
  }
}

export const getTopic = (topicId: string) => topics.find((topic) => topic.id === topicId) ?? topics[0];
export const getLesson = (lessonId: string) => topics.flatMap((topic) => topic.lessons).find((lesson) => lesson.id === lessonId);
export const getQuestion = (questionId: string) => questions.find((question) => question.id === questionId);
export const isLearnerVisible = (question: Question) => question.verification.status === "verified" || question.verification.status === "published";
export const getQuestionsForTopic = (topicId: string) => questions.filter((question) => question.topicId === topicId && isLearnerVisible(question));
export const getQuestionsForLesson = (lessonId: string) => questions.filter((question) => question.lessonId === lessonId && isLearnerVisible(question));
